### ISSUE TITLE
macOS 希望增加类似网易云音乐的顶部歌词和控制按钮

### ISSUE THREAD

**Issue by ckaqq** [sunzongzheng/music#1]
![image](https://user-images.githubusercontent.com/11495438/32936956-5468dba6-cbb1-11e7-8a2a-4b714c6dcb2f.png)
如图，看歌词和切歌很方便

**Comment by sunzongzheng** [comment]
get

**Comment by sunzongzheng** [comment]
https://github.com/sunzongzheng/music/releases

**Comment by ckaqq** [comment]
赞一个

**Comment by ckaqq** [comment]
希望歌词导航栏长度固定，无论歌词长短，现在如果歌词夹在两个图标中间，操作起来很蛋疼，网易云就是固定长度的，如果歌词太长会进行滚动

**Comment by ckaqq** [comment]
如果点击顶部歌词能打开主界面就更好了😊

**Comment by ckaqq** [comment]
发现一个顶部歌词的 bug，按住`command`键拖动菜单栏歌词时，三个图标不是一起移动的
![image](https://user-images.githubusercontent.com/11495438/33108992-102853be-cf7a-11e7-84aa-6601630958c2.png)

**Comment by sunzongzheng** [comment]
新版本用canvas画，这回跟网易云的表现一致了
