### ISSUE TITLE
歌单打不开了

### ISSUE THREAD

**Issue by ckaqq** [sunzongzheng/music#10]
![image](https://user-images.githubusercontent.com/11495438/41136659-dae4c1ca-6b09-11e8-871f-236bb352a98d.png)

如图，点击两个歌单都是显示网易云音乐排行榜

- 系统：macOS 10.13.4
- 版本：v1.1.3

**Comment by ckaqq** [comment]
新建的云歌单也打不开，新建的离线歌单能正常打开

**Comment by sunzongzheng** [comment]
get

**Comment by sunzongzheng** [comment]
已解决。更新[最新版](https://github.com/sunzongzheng/music/releases/tag/v1.1.4)
