### ISSUE TITLE
本地歌曲扫描路径不扫描子文件夹下的音乐

### ISSUE THREAD

**Issue by 11zi** [sunzongzheng/music#107]
存放音乐的文件夹下有一千多个文件夹, 文件夹里又有文件夹, 每个文件夹下面都有几首音乐, 总共5000多首歌......

**Comment by sunzongzheng** [comment]
现在的列表性能非常差，5000首歌会直接卡死。我近期没有维护，建议fork做个递归扫描+虚拟列表

**Comment by sunzongzheng** [comment]
递归扫描已加上，列表性能未优化，5000首歌仍然会卡死
