### ISSUE TITLE
排行榜请求不到任何信息 QQ和网易云都不行

### ISSUE THREAD

**Issue by zhangmingzhong619** [sunzongzheng/music#111]

**Comment by sunzongzheng** [comment]
这块目前请求的是服务端接口，需要把服务端跑起来

**Comment by sunzongzheng** [comment]
详细看[项目文档](https://github.com/sunzongzheng/player-be#player-be-)，实现登录还需要去对应平台注册应用

**Comment by zhangmingzhong619** [comment]
麻烦博主解答一下 谢谢&nbsp; 我是个小白&nbsp; 请问服务端需要运行那个脚本&nbsp; &nbsp;或者是服务端代码在哪？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunzongzheng/music"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 下午2:37
收件人:&nbsp;"sunzongzheng/music"<music@noreply.github.com&gt;;
抄送:&nbsp;"十"<704094067@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sunzongzheng/music] 排行榜请求不到任何信息 QQ和网易云都不行 (#111)





 
这块目前请求的是服务端接口，需要把服务端跑起来

**Comment by zhangmingzhong619** [comment]
麻烦博主您能给我说一下 服务端是需要跑起来那个脚本吗&nbsp; 还是有对应的服务端代码&nbsp; 谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunzongzheng/music"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月9日(星期三) 下午2:37
收件人:&nbsp;"sunzongzheng/music"<music@noreply.github.com&gt;;
抄送:&nbsp;"十"<704094067@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sunzongzheng/music] 排行榜请求不到任何信息 QQ和网易云都不行 (#111)





 
这块目前请求的是服务端接口，需要把服务端跑起来

**Comment by sunzongzheng** [comment]
上面贴的项目文档就是服务端项目地址了，目前项目很久没维护，没有开发能力可能无法跑起来，建议使用其他项目
