### ISSUE TITLE
本地导入的歌曲若不在线上存在则不能播放？

### ISSUE THREAD

**Issue by kqwyf** [sunzongzheng/music#113]
最近导入了一些歌曲，有一些在网易云上搜得到，另一些是其他渠道找来的，线上搜不到。全部放在本地歌曲文件夹后发现，线上能搜到的歌曲都能正常播放，但线上搜不到的歌曲点击播放时只有正在播放的标题切换为该歌曲，但实际播放的音乐仍然是上一首歌。

**Comment by sunzongzheng** [comment]
`线上搜不到`是指网易云搜不到，来源于QQ、虾米的吗。

QQ、虾米的获取音乐url的接口可能挂了

**Comment by kqwyf** [comment]
> `线上搜不到`是指网易云搜不到，来源于QQ、虾米的吗。
> 
> QQ、虾米的获取音乐url的接口可能挂了

不是的，`线上搜不到`是指所有音乐平台上都没有的音乐，例如我自己录制的mp3。

**Comment by sunzongzheng** [comment]
打开控制台看下报错，播放本地歌曲时是不会去做在线匹配的。怀疑是歌曲无法用浏览器的audio标签播放，是什么格式的歌曲？

**Comment by kqwyf** [comment]
是mp3格式。以下称能直接播放的音乐为正常音乐，否则为异常音乐。

双击异常音乐时控制台会进行2次报错，分别是：

> TypeError: Cannot read property 'name' of undefined
    at r.qualityText (renderer.be820d7….js:8)
    at Mr.get (renderer.be820d7….js:1)
    at Mr.evaluate (renderer.be820d7….js:1)
    at r.qualityText (renderer.be820d7….js:1)
    at render (renderer.be820d7….js:8)
    at r.e._render (renderer.be820d7….js:1)
    at r.a (renderer.be820d7….js:1)
    at Mr.get (renderer.be820d7….js:1)
    at Mr.run (renderer.be820d7….js:1)
    at kt (renderer.be820d7….js:1)
re	@	renderer.be820d7….js:1
ne	@	renderer.be820d7….js:1
ae	@	renderer.be820d7….js:1
e._render	@	renderer.be820d7….js:1
a	@	renderer.be820d7….js:1
Mr.get	@	renderer.be820d7….js:1
Mr.run	@	renderer.be820d7….js:1
kt	@	renderer.be820d7….js:1
(anonymous)	@	renderer.be820d7….js:1
le	@	renderer.be820d7….js:1
Async Call		
ir	@	renderer.be820d7….js:1
se	@	renderer.be820d7….js:1
Tt	@	renderer.be820d7….js:1
Mr.update	@	renderer.be820d7….js:1
$n.notify	@	renderer.be820d7….js:1
set	@	renderer.be820d7….js:1
update	@	renderer.be820d7….js:8
wrappedMutationHandler	@	/tmp/.mount_playerMa…/vuex.common.js:727
commitIterator	@	/tmp/.mount_playerMa…/vuex.common.js:393
(anonymous)	@	/tmp/.mount_playerMa…/vuex.common.js:392
_withCommit	@	/tmp/.mount_playerMa…/vuex.common.js:523
commit	@	/tmp/.mount_playerMa…/vuex.common.js:391
boundCommit	@	/tmp/.mount_playerMa…/vuex.common.js:336
(anonymous)	@	renderer.be820d7….js:8
a	@	renderer.be820d7….js:8
(anonymous)	@	renderer.be820d7….js:8
e.(anonymous function)	@	renderer.be820d7….js:8
r	@	renderer.be820d7….js:1
l	@	renderer.be820d7….js:1
(anonymous)	@	renderer.be820d7….js:1
t	@	renderer.be820d7….js:1
(anonymous)	@	renderer.be820d7….js:1
t.default.actions.play	@	renderer.be820d7….js:8
wrappedActionHandler	@	/tmp/.mount_playerMa…/vuex.common.js:734
dispatch	@	/tmp/.mount_playerMa…/vuex.common.js:439
boundDispatch	@	/tmp/.mount_playerMa…/vuex.common.js:333
local.dispatch	@	/tmp/.mount_playerMa…/vuex.common.js:664
mappedAction	@	/tmp/.mount_playerMa…/vuex.common.js:937
doPlay	@	renderer.be820d7….js:8
dblclick	@	renderer.be820d7….js:8
ie	@	renderer.be820d7….js:1
o	@	renderer.be820d7….js:1
Qo.n._wrapper	@	renderer.be820d7….js:1

以及

> TypeError: Cannot read property 'name' of undefined
    at r.qualityText (renderer.be820d7….js:8)
    at Mr.get (renderer.be820d7….js:1)
    at Mr.evaluate (renderer.be820d7….js:1)
    at r.qualityText (renderer.be820d7….js:1)
    at render (renderer.be820d7….js:8)
    at r.e._render (renderer.be820d7….js:1)
    at r.a (renderer.be820d7….js:1)
    at Mr.get (renderer.be820d7….js:1)
    at Mr.run (renderer.be820d7….js:1)
    at kt (renderer.be820d7….js:1)
re	@	renderer.be820d7….js:1
ne	@	renderer.be820d7….js:1
ae	@	renderer.be820d7….js:1
e._render	@	renderer.be820d7….js:1
a	@	renderer.be820d7….js:1
Mr.get	@	renderer.be820d7….js:1
Mr.run	@	renderer.be820d7….js:1
kt	@	renderer.be820d7….js:1
(anonymous)	@	renderer.be820d7….js:1
le	@	renderer.be820d7….js:1
Async Call		
ir	@	renderer.be820d7….js:1
se	@	renderer.be820d7….js:1
Tt	@	renderer.be820d7….js:1
Mr.update	@	renderer.be820d7….js:1
$n.notify	@	renderer.be820d7….js:1
set	@	renderer.be820d7….js:1
update	@	renderer.be820d7….js:8
wrappedMutationHandler	@	/tmp/.mount_playerMa…/vuex.common.js:727
commitIterator	@	/tmp/.mount_playerMa…/vuex.common.js:393
(anonymous)	@	/tmp/.mount_playerMa…/vuex.common.js:392
_withCommit	@	/tmp/.mount_playerMa…/vuex.common.js:523
commit	@	/tmp/.mount_playerMa…/vuex.common.js:391
boundCommit	@	/tmp/.mount_playerMa…/vuex.common.js:336
local.commit	@	/tmp/.mount_playerMa…/vuex.common.js:681
(anonymous)	@	renderer.be820d7….js:8
setTimeout (async)		
(anonymous)	@	renderer.be820d7….js:8
a	@	renderer.be820d7….js:8
(anonymous)	@	renderer.be820d7….js:8
e.(anonymous function)	@	renderer.be820d7….js:8
r	@	renderer.be820d7….js:1
l	@	renderer.be820d7….js:1
(anonymous)	@	renderer.be820d7….js:1
t	@	renderer.be820d7….js:1
(anonymous)	@	renderer.be820d7….js:1
t.default.actions.play	@	renderer.be820d7….js:8
wrappedActionHandler	@	/tmp/.mount_playerMa…/vuex.common.js:734
dispatch	@	/tmp/.mount_playerMa…/vuex.common.js:439
boundDispatch	@	/tmp/.mount_playerMa…/vuex.common.js:333
local.dispatch	@	/tmp/.mount_playerMa…/vuex.common.js:664
mappedAction	@	/tmp/.mount_playerMa…/vuex.common.js:937
doPlay	@	renderer.be820d7….js:8
dblclick	@	renderer.be820d7….js:8
ie	@	renderer.be820d7….js:1
o	@	renderer.be820d7….js:1
Qo.n._wrapper	@	renderer.be820d7….js:1

其中只有细微几行的差别。

此外，我刚才发现一些情况下也是可以播放异常音乐的。基本复现思路是首先播放正常音乐，然后双击某异常音乐，然后关闭软件，再启动软件，然后直接去播放刚才的异常音乐，此时异常音乐就可以播放。具体各种情况的表现如下：

1. 关闭时正在播放正常音乐A，打开后双击正常音乐A，软件将从上次位置继续播放A。
2. 关闭时正在播放正常音乐A，打开后双击正常音乐B，软件将从头播放B。
3. 关闭时正在播放正常音乐A，打开后双击异常音乐C，软件将从上次位置继续播放A。
4. 首先播放正常音乐A，然后双击异常音乐C，此时实际上仍在播放A，但进度条区域显示C的名称，然后关闭软件。重启软件后双击异常音乐C，软件将从上次A播放到的时刻继续播放C。
5. 首先播放正常音乐A，然后双击异常音乐C，此时实际上仍在播放A，但进度条区域显示C的名称，然后关闭软件。重启软件后双击异常音乐D，软件将从上次A播放到的时刻继续播放C。
6. 通过4行的方法播放异常音乐C，关闭软件，然后启动软件并双击异常音乐C，软件将从上次位置继续播放C。
7. 通过4行的方法播放异常音乐C，关闭软件，然后启动软件并双击异常音乐D，软件将从上次位置继续播放C（且进度条位置仍显示C的名称）。
8. 通过6行的方法播放异常音乐C，关闭软件，然后启动软件并双击异常音乐D，软件将从上次位置继续播放C（且进度条位置仍显示C的名称）。
9. 通过4行的方法播放异常音乐C，然后双击异常音乐D，然后关闭软件并重启，然后双击异常音乐D，软件将从上次C播放到的时刻继续播放D。
10. 通过4行的方法播放异常音乐C，然后双击异常音乐D，然后关闭软件并重启，然后双击异常音乐E，软件将从上次C播放到的时刻继续播放D。

**Comment by kqwyf** [comment]
补充：
操作系统：Manjaro Linux
软件版本：1.2.0 （AppImage）

**Comment by sunzongzheng** [comment]
使用的是不是release里下载的版本？

**Comment by kqwyf** [comment]
是的。

**Comment by sunzongzheng** [comment]
代码已解决，需自行编译

**Comment by kqwyf** [comment]
已自行编译测试，问题已解决。
