### ISSUE TITLE
Mac版歌不能循环播放

### ISSUE THREAD

**Issue by GZHermit** [sunzongzheng/music#12]
虽然有多种播放模式
但是每次播放一遍之后就停掉了，需要手动点播放。

不过产品做得非常棒！喜欢！加油！

**Comment by sunzongzheng** [comment]
歌单内播放以及排行榜内播放应该没有这个问题吧？

指的应该是播放 搜索结果歌曲？由于歌曲来源于三个平台，虽然做了去重，但是还是会有可能重复，所以播放搜索结果暂时没有把搜索结果的其他歌曲加入播放列表。

下个版本考虑也加入播放列表，感谢支持～

**Comment by sunzongzheng** [comment]
已更新
