### ISSUE TITLE
现在没用了吗

### ISSUE THREAD

**Issue by James-jqy** [sunzongzheng/music#121]
下载安装之后，都不能听歌了

**Comment by sunzongzheng** [comment]
最新版需要下载代码自行编译，部分api失效，基本能用

**Comment by James-jqy** [comment]
我好菜，不知道咋编译😂------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Suen&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月5日(星期四) 上午10:37
收件人:&nbsp;&quot;sunzongzheng/music&quot;<music@noreply.github.com&gt;;
抄送:&nbsp;&quot;James-jqy&quot;<2287061933@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [sunzongzheng/music] 现在没用了吗 (#121)

**Comment by sunzongzheng** [comment]
看完README说哪里不会吧。完全动不了手的话不推荐使用了，因为项目年久失修，可能越深入觉得难用，建议使用其他方案
