### ISSUE TITLE
node 15.2.1 build failed

### ISSUE THREAD

**Issue by closetool** [sunzongzheng/music#122]
使用manjaro 20 node v15.2.1在项目根目录下运行yarn指令时,显示错误
```
error apicache@1.5.3: The engine "node" is incompatible with this module. Expected version ">=6.2.0 <13". Got "15.2.1"
error Found incompatible module.
```

**Comment by sunzongzheng** [comment]
musicApi依赖的apicache目前只支持node13，暂时先在低版本下编译吧
https://github.com/kwhitley/apicache/blob/f27cb2b30719e8eb35ef98c6c019dd1d5ec96732/package.json#L13
