### ISSUE TITLE
1.3.0 版本，Ctrl + R 快捷键被占用

### ISSUE THREAD

**Issue by JadeVane** [sunzongzheng/music#131]
感谢作者开发音乐湖，网易为了让用户卸载 play 版客户端而转向国内毒瘤app可谓良苦用心，直接不能登录了，幸好有音乐湖。

今天刚开始用，发现一个问题，就是 `Ctrl` + `R` 快捷键被占用了，看到另外的 issue 显示 1.2.0 有一个去掉了快捷键占用的包，当前的最新版（1.3.0）是否有这样的包？或者能否提供一个去掉这个快捷键的方法？`Ctrl` + `R` 是很常用的快捷键了，被全局快捷键占用确实很不方便。。。

**Comment by sunzongzheng** [comment]
确实是一个遗漏的BUG
已解决，等稍后发版，或者你拉最新的代码手动构建也可以

**Comment by JadeVane** [comment]
@sunzongzheng 还发现个问题，全局快捷键改不了，即使显示已经更改，但使用的仍然是默认的快捷键。

例如播放快捷键为：`Ctrl` + `Alt` + `空格`，改为 `Ctrl` + `Alt` + `P` 后，仍然只能使用 `Ctrl` + `Alt` + `空格` 播放

**Comment by sunzongzheng** [comment]
> @sunzongzheng 还发现个问题，全局快捷键改不了，即使显示已经更改，但使用的仍然是默认的快捷键。
> 
> 例如播放快捷键为：`Ctrl` + `Alt` + `空格`，改为 `Ctrl` + `Alt` + `P` 后，仍然只能使用 `Ctrl` + `Alt` + `空格` 播放

仍然是BUG，已解决。
可以拉最新代码构建，或者在更改完快捷键后，重新勾选`启用全局快捷键`，也能暂时使用

**Comment by JadeVane** [comment]
试过已经可以了 :tada:
