### ISSUE TITLE
只能以未登录状态导入网易云歌单

### ISSUE THREAD

**Issue by JadeVane** [sunzongzheng/music#134]
导入网易云音乐的歌单时，选择的歌单内有 39 首歌，但导入歌单只能识别前几首歌，这前几首歌就是使用未登录状态打开歌单时显示的内容

![image](https://user-images.githubusercontent.com/34258753/111404951-9c802a80-870a-11eb-9474-b135dc11556a.png)

![image](https://user-images.githubusercontent.com/34258753/111405024-bc175300-870a-11eb-9e1d-a83bdf883a6f.png)

![image](https://user-images.githubusercontent.com/34258753/111405076-d0f3e680-870a-11eb-9c56-7143a0360df6.png)

**Comment by sunzongzheng** [comment]
先去设置里绑定网易云账号，再导入试试看

应该是网易云接口做了限制，不登录的时候看不到完整歌单，不确定有解，需要去找一下api

**Comment by JadeVane** [comment]
已经绑定网易云帐号，应该不是这个问题

**Comment by sunzongzheng** [comment]
> 已经绑定网易云帐号，应该不是这个问题

提供下你的歌单ID，我这边测试自己的歌单，绑定之后就可以看到完整列表了

**Comment by JadeVane** [comment]
网易云的歌单：`2234213763`

**Comment by sunzongzheng** [comment]
我测试下来，自己创建的歌单可以完整导入，别人的歌单就只能看到前20首

https://neteasecloudmusicapi.vercel.app/#/?id=%e8%8e%b7%e5%8f%96%e6%ad%8c%e5%8d%95%e8%af%a6%e6%83%85
需要修改下api，内部调两个接口去获取完整列表

**Comment by JadeVane** [comment]
要怎么修改，我不大了解 nodejs

**Comment by sunzongzheng** [comment]
> 要怎么修改，我不大了解 nodejs

需要调试并修改这个项目：https://github.com/sunzongzheng/musicApi/
然后在music这个项目更新依赖才行

等我有空看下吧

**Comment by sunzongzheng** [comment]
拉取最新代码，然后执行`yarn upgrade @suen/music-api`，然后看看客户端内是否已经能获取到完整歌单

**Comment by JadeVane** [comment]
最新版已解决，不过歌曲顺序被打乱了。。。

**Comment by sunzongzheng** [comment]
> 最新版已解决，不过歌曲顺序被打乱了。。。

可以贴一下打乱的对比图看下

**Comment by JadeVane** [comment]
### 这是原本的顺序

![image](https://user-images.githubusercontent.com/34258753/111957044-7ac9dd80-8b26-11eb-8261-e61be90b7e7d.png)
![image](https://user-images.githubusercontent.com/34258753/111957145-992fd900-8b26-11eb-87d7-429199f8b029.png)

### 这是抓取来的顺序

![image](https://user-images.githubusercontent.com/34258753/111956955-608fff80-8b26-11eb-8a88-47c37c123187.png)
![image](https://user-images.githubusercontent.com/34258753/111957246-b4024d80-8b26-11eb-836a-106131d6652f.png)
![image](https://user-images.githubusercontent.com/34258753/111957261-bc5a8880-8b26-11eb-8e1c-ad9511edfbb5.png)
