### ISSUE TITLE
网址连接的时候有bug,在我mac上无法查看云歌单

### ISSUE THREAD

**Issue by marongxing** [sunzongzheng/music#140]
https://github.com/sunzongzheng/music/blob/e68d60ff4e011c283e00ebd5c32b6e101b9eab87/src/renderer/util/http.js#L14

apiaddr尾部部可能带有'/'，config.url 开头也可能带有'/'
所以两者连接时可能会出现'apiaddr//url' 或者 'apiaddrurl'的情况

**Comment by sunzongzheng** [comment]
最新的commit已经对path做了统一
https://github.com/sunzongzheng/music/commit/e68d60ff4e011c283e00ebd5c32b6e101b9eab87
约定是全局配置中不加'/'，每个请求需加上，可自行编译最新版本先解决问题

确实还可以再做一层兼容，兼容你上面列的这两种异常情况

**Comment by marongxing** [comment]
搞定
