### ISSUE TITLE
搜索框不能粘贴

### ISSUE THREAD

**Issue by LiuKaHo** [sunzongzheng/music#15]
今天第一次用，很喜欢这个软件，解决了要下好几个软件的困境，但因为我听的歌大多是日文的，想粘贴歌名到搜索框但发现不管用 Command+V 还是右键都不能粘贴

**Comment by sunzongzheng** [comment]
get

**Comment by LiuKaHo** [comment]
不好意思。。忘记说了。。我是用 player-1.1.7-mac 这个版本的
