### ISSUE TITLE
从网易云导入歌单后，失效的歌能从qq音乐重新找吗？

### ISSUE THREAD

**Issue by rj8928** [sunzongzheng/music#16]
网易云歌单很多歌没版权下架了，导入后还是听不了，能自动换源就好了。还有右侧滑动条太窄了，按不到。。。

**Comment by sunzongzheng** [comment]
- 自动换源考虑过，重点考虑的问题是我能想到的逻辑不可靠。调搜索接口，取`同歌名`、`歌手名`的第一条搜索结果吗？
- 滚动条下个版本增加宽度。

**Comment by rj8928** [comment]
现在是之前没版权的歌处于灰色不可播放状态，可以考虑选中增加个更换源按钮，点击后自动搜索歌名让用户自己选择结果进行换源(不要打我)。

**Comment by sunzongzheng** [comment]
可以，加入版本计划 :smirk:
