### ISSUE TITLE
搜索“曾经的你”，内容为空白

### ISSUE THREAD

**Issue by ckaqq** [sunzongzheng/music#2]
![image](https://user-images.githubusercontent.com/11495438/33003998-2a54803c-cdf9-11e7-9df8-7cdb4c25e3e5.png)
![image](https://user-images.githubusercontent.com/11495438/33004001-312ad974-cdf9-11e7-8312-df0e072d184c.png)

**Comment by sunzongzheng** [comment]
get

**Comment by sunzongzheng** [comment]
https://github.com/sunzongzheng/music/releases

**Comment by ckaqq** [comment]
都要重构了，还修复这个 bug 干嘛...

测试了一下，确实修复了，速度好评～
