### ISSUE TITLE
无法获取网络,请求失败

### ISSUE THREAD

**Issue by youyiqin** [sunzongzheng/music#22]
显示请重试

**Comment by sunzongzheng** [comment]
是在进入程序的时候提示的吗

**Comment by youyiqin** [comment]
进入后刷新界面提示的，但是可以登录社交账号。我用深度社区的网易云音乐最近也有网络问题，可能有其他原因导致。

**Comment by sunzongzheng** [comment]
有这个提示之后，有功能无法使用吗，比如排行榜无法加载，搜索没有结果。如果还可以重现的话，可以把完整错误提示提供一下吗
