### ISSUE TITLE
【建议】可以做一个deb的包吗？

### ISSUE THREAD

**Issue by JAYRANRAIN** [sunzongzheng/music#23]
刚下载了appimage的包，体验一下，希望后续可以加入deb的包！

**Comment by rekols** [comment]
搞一个deb吧,哈哈哈

**Comment by sunzongzheng** [comment]
@rekols @JAYRANRAIN 问一个专业的问题，deb和AppImage包的区别是啥？

**Comment by rekols** [comment]
@sunzongzheng   appimage 每个linux发行版都能运行，deb是debian的软件包，所以只能在debian发行版上安装。

**Comment by JAYRANRAIN** [comment]
在我电脑上这两种包区别就是APPimage必须每次找到文件，点击打开，不可以放在dock栏上，所以有一些不方便。deb就没有这样的问题，还有APPimage好像是依赖关系独立的吧，在linux的不同发行版上都可以用。看到很多大佬做的包都有deb的，方便安装，升级也比较好升级。

**Comment by sunzongzheng** [comment]
@rekols 那为啥你们偏爱deb...因为可以用系统的包管理器安装与卸载吗

**Comment by rekols** [comment]
@sunzongzheng 因为debian系用户挺多，逃 （

**Comment by rekols** [comment]
deb包升级，一般都是直接覆盖安装的。

**Comment by rekols** [comment]
可以上架我们的 deepin 应用商店，哈哈。

**Comment by sunzongzheng** [comment]
@rekols deb包 软件内有办法实现自动更新吗。
现在云歌单部分是跑在自己的一台小鸡上，考虑好了稳定性可以考虑上 deepin 商店哈哈

**Comment by rekols** [comment]
@sunzongzheng   好像还没什么好办法，可以做个版本更新的提示让用户安装。。。

**Comment by rekols** [comment]
@sunzongzheng  这个可以有。

**Comment by sunzongzheng** [comment]
已更新

**Comment by rekols** [comment]
赞一个。

**Comment by rekols** [comment]
不过player这个名字太霸气了，有可能会跟其他包冲突。  (

**Comment by sunzongzheng** [comment]
@rekols 下个版本改一下

**Comment by sunzongzheng** [comment]
@rekols 我给你们应用投递的邮箱发了邮件，有没有快速通道走一下 :relaxed:

**Comment by rekols** [comment]
@sunzongzheng 国庆后处理。

**Comment by sunzongzheng** [comment]
@rekols 行

**Comment by rekols** [comment]
@sunzongzheng 有人说了收到了，信息不足，等信息完整后建tower任务处理。  （
