### ISSUE TITLE
可以换个图标？

### ISSUE THREAD

**Issue by rekols** [sunzongzheng/music#24]
![deepinscreenshot_dde-launcher_20180824114229](https://user-images.githubusercontent.com/9636382/44563908-f9094c00-a792-11e8-98d0-dad830b1d96e.png)

加个底色哈。。。

**Comment by sunzongzheng** [comment]
主要不会画图...如果是黑色壁纸的时候其实更加难受...这个需要寻找一下😂

**Comment by rekols** [comment]
看一下这个怎么样：
https://dstore-metadata.deepin.cn/images/cocomusic_icon.svg

https://dstore-metadata.deepin.cn/images/apps.com.tongyong.xxbox_icon.svg
https://dstore-metadata.deepin.cn/images/all.fm_icon.svg

**Comment by sunzongzheng** [comment]
1、3已经有人用了，2看起来比较常规，我换了一个先观望一下效果哈, 不行的话我再去尝试找一下设计师朋友 :satisfied:

https://github.com/sunzongzheng/music/blob/dev/build/icons/256x256.png

**Comment by rekols** [comment]
这个太丑了。。

**Comment by rekols** [comment]
快去找个设计师，哈哈哈

**Comment by sunzongzheng** [comment]
可以，周一我去找设计师去

**Comment by rekols** [comment]
All right.
