### ISSUE TITLE
how to compile?

### ISSUE THREAD

**Issue by rekols** [sunzongzheng/music#25]
RT

**Comment by sunzongzheng** [comment]
````js
yarn build 
````
or 
````js
npm run build
````

https://github.com/sunzongzheng/music/blob/59c959d33398b3872d4cd926b0646d90fb71cdda/package.json#L9

**Comment by rekols** [comment]
在 npm install 的时候出错了。

**Comment by sunzongzheng** [comment]
贴一下报错看看，是不是electron下不下来？

**Comment by rekols** [comment]
rekols@rekols-PC:~/web/music$ cnpm install
npm WARN deprecated babel-preset-babili@0.1.4: babili has been renamed to babel-minify. Please update to babel-preset-minify
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @suen/electron-updater@^1.0.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'player'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rekols/.npm/.cache/cnpm/_logs/2018-08-25T11_19_23_478Z-debug.log

**Comment by sunzongzheng** [comment]
再试一下。
原因是cnpm的包更新不及时，我刚刚已经[刷新](https://npm.taobao.org/package/@suen/electron-updater)了
或者直接换成npm就没有问题了，建议装依赖的时候开一下proxychains :satisfied: ，cnpm可能还会有其他奇怪的问题，例如cnpm装的包跟npm装的包不兼容，生成.lock文件后到vps上安装较慢等问题

**Comment by rekols** [comment]
神奇了

**Comment by rekols** [comment]
刚刚的cnpm install 一次就行了

**Comment by sunzongzheng** [comment]
cnpm可能比较流行的包才会同步的快，我这种私人发布，下载量极低的包，即使是两个月以前就更新了，也需要自己去[手动同步](https://npm.taobao.org/package/@suen/electron-updater)...

**Comment by rekols** [comment]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@babel/runtime/core-js/promise'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/rekols/web/music/releases/linux-unpacked/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/rekols/web/music/releases/linux-unpacked/resources/app.asar/node_modules/@suen/electron-updater/dist/github-adapter.js:10:39)
    at Object.<anonymous> (/home/rekols/web/music/releases/linux-unpacked/resources/app.asar/node_modules/@suen/electron-updater/dist/github-adapter.js:121:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)

**Comment by rekols** [comment]
运行的时候一直卡在了这   (

**Comment by sunzongzheng** [comment]
看一下node_modules目录下是不是没有`'@babel/runtime/core-js/promise'`这个包，把node_modules全删了，重新装一次试试

**Comment by rekols** [comment]
删了又执行了一下 cnpm install 还是一样。

**Comment by sunzongzheng** [comment]
node版本是多少？

**Comment by rekols** [comment]
node 版本是　10.9.0，我用npm装装看

**Comment by rekols** [comment]
npm安装也是这样

**Comment by rekols** [comment]
确实没有这个　　@babel/runtime/core-js/promise

**Comment by sunzongzheng** [comment]
node回退到lts试试，8

**Comment by sunzongzheng** [comment]
@rekols  上次找不到`@babel/runtime/core-js/promise`解决了吗？又有一个windows的大兄弟遇到了，我这边调试了一下，发现用npm装就会没有这个文件夹，用yarn安装就有
