### ISSUE TITLE
歌单无法获取热歌榜，排行榜的各个歌单等等

### ISSUE THREAD

**Issue by Lancelothe** [sunzongzheng/music#27]

**Comment by sunzongzheng** [comment]
可以提供一下截图吗，看看具体是哪个页面

**Comment by sunzongzheng** [comment]
我这边检查正常
![image](https://user-images.githubusercontent.com/12635613/44834618-43dc0580-ac64-11e8-9143-8040e976b125.png)
![image](https://user-images.githubusercontent.com/12635613/44834643-4f2f3100-ac64-11e8-97e1-9c91a18808a8.png)

**Comment by sunzongzheng** [comment]
你指的是导入歌单不能导入排行榜歌曲吧。
如果排行榜加一个允许切换网易云/QQ音乐的榜单，再在榜单的位置加个批量添加到歌单，应该就可以解决你的需求了。
加入版本计划~

**Comment by sunzongzheng** [comment]
@Lancelothe 已加上QQ榜单和榜单添加至歌单功能，还有问题可reopen或新开issues~

**Comment by Lancelothe** [comment]
@sunzongzheng 感谢，解决了，就是切换不太好找，😄
