### ISSUE TITLE
对于音乐播放器的建议

### ISSUE THREAD

**Issue by StevenByte** [sunzongzheng/music#31]
因为体验了很长时间所以提出一些不成熟的建议：
   1.希望可以加上歌词翻译
   2.希望首页会有歌曲分类
   3.希望出RPM包

**Comment by sunzongzheng** [comment]
感谢建议~全都已加入版本计划豪华午餐！
2、3应该很快，
1 我需要研究研究哈

**Comment by rekols** [comment]
酷狗api呢   滑稽（

**Comment by sunzongzheng** [comment]
@rekols 你听的歌现在这三大平台都没有吗 :astonished:

**Comment by sunzongzheng** [comment]
@StevenByte rpm 包已提供，[更新最新版](https://github.com/sunzongzheng/music/releases/tag/v1.1.10)
其他的等下次更新吧~

**Comment by sunzongzheng** [comment]
@StevenByte 最新版加了`精选`

**Comment by sunzongzheng** [comment]
@StevenByte 歌词翻译也加上了，还有其他问题可reopen或新开issues~
