### ISSUE TITLE
【FeatureRequest】修改播放模式/补充快捷键/退出软件

### ISSUE THREAD

**Issue by zqso** [sunzongzheng/music#35]
您好，

之前提了个添加快捷键的FeatureRequest，非常感谢作者如此之快地添加上了，现在用得很顺手。
又有几个小需求：

1. 能否将“上一首”“下一首”切换模式切换成网易云音乐的切换模式？
即，在目前版本中，“单曲循环”播放模式中点击“上/下一首”，歌曲只是重新播放当前音乐，而不是切换到上/下一首进行单曲循环，这是QQ音乐和Vox音乐播放器的播放模式; 相比之下，网易云音乐在“单曲循环”模式下点击“上/下一首”是可以切到上/下一首进行单曲循环的，更方便一些。

2. 能否在快捷键设置里加入“播放模式切换”的全局快捷键选项，以切换单曲循环/列表循环/随机播放？

3. 能在Menubar里加入Quit MusicLake的按键么？现在只能通过杀进程。

多谢大佬。

**Comment by sunzongzheng** [comment]
都可以，加入版本计划~
你希望快捷键切换是 一个键切三种模式 还是 三个键对应三个模式？

**Comment by zqso** [comment]
> 都可以，加入版本计划~
> 你希望快捷键切换是 一个键切三种模式 还是 三个键对应三个模式？

倾向于只用一个按键，足够方便切换了。
三个键太浪费键盘快捷键了吧，哈哈。
多谢～

**Comment by sunzongzheng** [comment]
后续问题到 #38 讨论
