### ISSUE TITLE
下载功能不可用

### ISSUE THREAD

**Issue by mydy1987** [sunzongzheng/music#36]
好想用你的下载功能呀

**Comment by sunzongzheng** [comment]
为了尽可能避免影响到各大音乐平台的利益，下载功能的优先级一直比较靠后。
这两天musicApi我增加了`能否免费下载`字段，最近会更新下载功能，但是也是不允许下载被`限制`的歌曲的~
为了活得更久~ 😄

**Comment by rekols** [comment]
哈哈哈

**Comment by sunzongzheng** [comment]
@mydy1987 更新最新版
