### ISSUE TITLE
ubuntu18.04中每次都要重新登录

### ISSUE THREAD

**Issue by lfxyl** [sunzongzheng/music#37]

**Comment by lfxyl** [comment]
没有其他问题，就是每次都要重新登录。我是用deb包安装的

**Comment by sunzongzheng** [comment]
> 没有其他问题，就是每次都要重新登录。我是用deb包安装的

我这边也是用deb包安装测试的。

无法自动登录的时候，进入程序以后有没有提示`请检查网络连接`？

**Comment by lfxyl** [comment]
> > 没有其他问题，就是每次都要重新登录。我是用deb包安装的
> 
> 我这边也是用deb包安装测试的。
> 
> 无法自动登录的时候，进入程序以后有没有提示`请检查网络连接`？

没有

**Comment by lfxyl** [comment]
更新最新版本后可以了

**Comment by sunzongzheng** [comment]
好的～
