### ISSUE TITLE
能调整下布局吗？吧最大最小关闭放在右边。

### ISSUE THREAD

**Issue by wudong4612** [sunzongzheng/music#44]
就是正常win方向，还有快捷键能禁用， ？

建议可以自己设置安装目录。

**Comment by sunzongzheng** [comment]
快捷键会影响到你的使用吗？

**Comment by wudong4612** [comment]
会有一点点，影响不大。主要是那个 最大最小关闭，特别不习惯在左边。还有安装目录，直接安装道才盘。
