### ISSUE TITLE
有交流群吗？

### ISSUE THREAD

**Issue by MemoryCollection** [sunzongzheng/music#45]
已经添加道歌单和已经添加喜欢的音乐，没有区别，看不出来是否已经收录道歌单里。

**Comment by sunzongzheng** [comment]
链接加入群聊【音乐湖交流群】：https://jq.qq.com/?_wv=1027&k=5xPZe7V

添加喜欢的音乐是在哪个界面操作的？

**Comment by rekols** [comment]
建一个 telegrame 群把

**Comment by rekols** [comment]
@sunzongzheng 加了

**Comment by MemoryCollection** [comment]
已经加群了。
