### ISSUE TITLE
build问题请教

### ISSUE THREAD

**Issue by kakalote2008** [sunzongzheng/music#47]
本地运行npm run dev没问题，npm run build也能成功，不过打包出的dmg与app都不可用，报错如下
![image](https://user-images.githubusercontent.com/26380298/47276367-19198800-d5e9-11e8-9194-a3fffbac1c35.png)
我之前没用过electron，前端也很渣，求大神指点。。。

**Comment by sunzongzheng** [comment]
同 #48
