### ISSUE TITLE
build问题请教

### ISSUE THREAD

**Issue by kakalote2008** [sunzongzheng/music#48]
本地npm run dev正常运行，npm run build也没有报错，但是运行dmg的时候报错如下
![image](https://user-images.githubusercontent.com/26380298/47276438-934a0c80-d5e9-11e8-89fa-f092efb80086.png)
我第一次用electron，弱问下如何正确打包该项目，谢谢大神

**Comment by sunzongzheng** [comment]
贴一下`node_modules/@suen/electron-updater/package.json`的版本看一下

**Comment by sunzongzheng** [comment]
github今天炸了，可以加Q群详聊

**Comment by sunzongzheng** [comment]
超过一个月未更新

**Comment by macheng2017** [comment]
step 1. rm node_modules 2. yarn 3. yarn build  使用的是npm 就会报错
