### ISSUE TITLE
希望能抓取网易云音乐的评论

### ISSUE THREAD

**Issue by ckaqq** [sunzongzheng/music#5]
希望能够根据歌名获取网易云音乐的高赞评论，歌曲不一定来自网易云音乐

**Comment by sunzongzheng** [comment]
get

**Comment by sunzongzheng** [comment]
目标是`网易云的高赞评论`还是`歌曲评论`？
（qq音乐和虾米也有评论）

**Comment by ckaqq** [comment]
我更想看的是`网易云高赞评论`，其他地方评论也很精彩的话当然也可以

**Comment by Chengyumeng** [comment]
https://github.com/Chengyumeng/spider163这个项目解决了

**Comment by Chengyumeng** [comment]
这个项目解决了：https://github.com/Chengyumeng/spider163

**Comment by sunzongzheng** [comment]
其实qq网易云虾米的评论已经解析成功，不过qq网易云的评论系统逻辑是不一样的，最近需求又过于饱和，一直没有更新...

**Comment by sunzongzheng** [comment]
已更新，有体验上的问题可reopen
