### ISSUE TITLE
打开两次musiclake会出现两个不同的播放器？

### ISSUE THREAD

**Issue by fredwzz** [sunzongzheng/music#55]
感谢开发这么好的东西，网易云已经无歌可听，linux又只有网易云可选，实在是好东西阿。
但是我发现的问题是点几次musiclake就会出现几个不同的播放器，而且这些播放器之间的数据貌似是不共享的，下载完的歌曲以及建立好的歌单下次在打开就没了，虽然下载文件夹里有歌曲存在，但是不识别还是怎么的。

**Comment by sunzongzheng** [comment]
下载歌曲历史现在仅仅是下载时存储在客户端，可能是多开导致历史存在几个客户端了，我这边看一下能不能限制多开。
建立好的歌单下次再打开就没了应该也是指离线歌单吧？离线歌单同下载历史，存储在客户端，可能是多开客户端不共享数据。云歌单应该没有这个问题

**Comment by fredwzz** [comment]
音乐播放器应该是没有多开的需求吧，多开了还会多显示用不到的播放器，dock里也不好看
