### ISSUE TITLE
MusicLake for MacOS 崩溃退出

### ISSUE THREAD

**Issue by zqso** [sunzongzheng/music#59]
使用环境：Focus for Mac (Mojave) 开启新的 start focus 时会自动启动我 Keyboard Maestro 里的一个Macro, 这时候 MusicLake (1.2) 就会崩溃，不知道是啥原因。

附: Console 文件。
[MusicLake_2018-11-03-153043_Zz-2.crash.zip](https://github.com/sunzongzheng/music/files/2544717/MusicLake_2018-11-03-153043_Zz-2.crash.zip)

**Comment by zqso** [comment]
你好，

退出的原因找到了，
是我自己用 Keyboard Maestro.app 写了一条定时关闭重启 MusicLake 的 macro。

这个 issue 可以关闭了。
谢谢～！

**Comment by sunzongzheng** [comment]
哈哈，我都还没找到复现的办法
