### ISSUE TITLE
archlinux中怎么解决依赖

### ISSUE THREAD

**Issue by Howard-00** [sunzongzheng/music#6]

**Comment by sunzongzheng** [comment]
没有使用过archlinux，只测试了ubuntu。请问依赖问题是在什么场景下发生的？安装deb时还是打开程序时？

**Comment by qlmlove** [comment]
在终端运行,然后看缺少什么东西,然后pacman或者yaourt安装那些缺失的包,然后试试看能不能运行,如果可以的话,以后就可以双击appImage文件运行了,我也时arch,不过我的只是自动更新有问题,现在1.1.10,自动更新会变成1.1.9,而且点任何歌单之后还会报错,所以建议你直接下载release里边的1.1.10,别开自动更新吧 @Howard-00

**Comment by sunzongzheng** [comment]
@qlmlove 点任何歌单报错是报什么错？可以贴一下吗

**Comment by qlmlove** [comment]
报错的时候的弹窗
![弹窗报错](http://wx1.sinaimg.cn/mw690/0060lm7Tly1fv7my4xx1lj30dl07pt92.jpg)
报错的时候终端输出的结果
![终端里输出](http://wx1.sinaimg.cn/mw690/0060lm7Tly1fv7my4yc22j30u3043jsg.jpg)

**Comment by sunzongzheng** [comment]
@qlmlove 重新下载release里的最新版看看还有没有这个问题

**Comment by qlmlove** [comment]
手动下载的1.1.10没问题,在这是开启自动更新之后会自动下载1.1.9,然后1.1.9报上边这个错,我已经把自动更新关了,如果可以的话请检查一下您的代码中`检测新版本`的部分,可能有些问题吧
下边截图中,上一条是github直接下载的,下一条是自动更新的
![下载文件截图](http://wx3.sinaimg.cn/mw690/0060lm7Tly1fv7rbv0pzpj307001q3yd.jpg
)

**Comment by sunzongzheng** [comment]
@qlmlove 好的，感谢反馈~
