### ISSUE TITLE
任务栏只有一个选项，不如直接左键打开，不用右键菜单了

### ISSUE THREAD

**Issue by scutmarx** [sunzongzheng/music#64]
支持作者

**Comment by scutmarx** [comment]
> 是指托盘图标吗

对的，我用的是ubuntu 18.04,还有就是不能设置默认的下载目录

**Comment by sunzongzheng** [comment]
官方文档写的是一些平台上单击事件无效，所以最好是用右键菜单保持平台一致哈。下载目录功能暂时没有，我记一下，稍后更新～
