### ISSUE TITLE
ctrl + r

### ISSUE THREAD

**Issue by scutmarx** [sunzongzheng/music#65]
我在ubuntu 上的终端想要搜索 历史命令时，ctrl + r 突然打开了musiclake的调试控制台，但我在快捷方式那里又没看到这个绑定

**Comment by sunzongzheng** [comment]
复现了...我写的是Control + Q + W + E + R打开，最后竟然变成了ctrl + r打开...
![image](https://user-images.githubusercontent.com/12635613/48241548-66339180-e412-11e8-9fe5-d8af1993f576.png)


我把组合键去掉打了个包，你先用着
https://cdn.zzsun.cc/zzsun-cdn/music/player-1.2.0-linux-delete-console-shortcut.deb
