### ISSUE TITLE
深度系统下ctrl+r默认打开console

### ISSUE THREAD

**Issue by kearons** [sunzongzheng/music#74]
1. 深度系统15.8中，不论在哪里按下ctrl+R都会打开软件的调试控制台
2. 播放歌曲的时候点击播放都是直接替换了播放列表，不能只听自己想听的歌好像。

最后还是支持下作者，这款软件还是非常不错的！

**Comment by sunzongzheng** [comment]
1. 同#65，是一个bug，先用这个包
https://cdn.zzsun.cc/music/player-1.2.0-linux-delete-console-shortcut.deb

**Comment by kearons** [comment]
感谢作者回复～
其实就是像这种场景，比如我想听一首歌了，我搜出来很多，有原唱有翻唱很多版本，但是我只是想听原版的，然后我又想听另一首歌，但是这时候播放列表就没办法了。
就像维护一个临时播放列表的概念，网易啊qq都是这样的

**Comment by sunzongzheng** [comment]
网易QQ具体是怎么操作？我这边尝试先播放歌单，然后播放搜索结果中的歌曲，等到下一首的时候没有自动恢复播放之前的歌单

**Comment by sunzongzheng** [comment]
再次尝试了一下网易，网易的逻辑是这样，`右键播放` = `添加单首到歌单并播放`，`双击播放` = `播放全部并替换歌曲列表`，这样的逻辑还是可以接受，稍后更新一下

**Comment by kearons** [comment]
赞～
