### ISSUE TITLE
可以写一下安装指南吗

### ISSUE THREAD

**Issue by hanshoukai** [sunzongzheng/music#75]
感觉这是一个好开源项目，自己想在本地运行起来。可不知道怎么操作，可以写一个安装部署指南吗？

**Comment by sunzongzheng** [comment]
有node环境，执行以下命令就可以跑起来
````js
npm i
npm run dev
````
如果依赖装不下来需要开代理
其他命令见： https://github.com/sunzongzheng/music/blob/6bedaf7eb650f4dd5d9ebadc13d235939522c666/package.json#L8
