### ISSUE TITLE
代理功能

### ISSUE THREAD

**Issue by retaw106** [sunzongzheng/music#78]
windows平台能否加入proxy功能？好像默认的是直接连接，没有走系统代理

**Comment by sunzongzheng** [comment]
可以加，你那边是在海外吗，大陆应该没有这个需求吧？

**Comment by sunzongzheng** [comment]
你可以暂时用`Proxifier`设置应用代理，不太清楚你的`系统代理`是什么级别的，我这边用`Proxifier`设置是有效的

**Comment by qcq** [comment]
may you add a proxy setup under one menu.
