### ISSUE TITLE
本地歌曲问题

### ISSUE THREAD

**Issue by yesmiley** [sunzongzheng/music#82]
1. 文件直接拖到窗口变成了Chrome浏览器的播放？难道这是个套壳的浏览器吗（笑喷）
1. 本地扫描歌曲文件夹不能改吗

**Comment by sunzongzheng** [comment]
1. 你没有猜错，就是套壳
2. 本地歌曲功能还是乞丐版，优先级比较低哈

**Comment by YorickGu** [comment]
可以加入本地扫描歌曲的文件改变的功能嘛？这样我就可以替代那些其他的歌曲软件直接用这个了

**Comment by sunzongzheng** [comment]
@YorickGu  这个功能在版本计划内，但是目前的主要精力是做重构

**Comment by sunzongzheng** [comment]
已加上
