### ISSUE TITLE
请问是否支持Windows32位操作系统呢？

### ISSUE THREAD

**Issue by xnbx2012** [sunzongzheng/music#84]
### 如题：请问是否支持32位的Windows 7旗舰版？
下载了Windows可执行文件exe后，提示只能安装在64位系统，请问是否支持32位系统呢？谢谢！如果不支持，未来是否会进行适配呢？再次感谢！

**Comment by sunzongzheng** [comment]
由于受到QQ音乐、网易云音乐的警告函，现已关闭服务
支持32位系统，有兴趣可以自行打包，文档见 https://www.electron.build/
