### ISSUE TITLE
关闭服务了？

### ISSUE THREAD

**Issue by Mackel123** [sunzongzheng/music#86]
关闭服务了？建议关闭掉windows客户端，因为windows体量太大，容易被秒杀

**Comment by sunzongzheng** [comment]
关闭了，可以暂时改改，自用离线歌单

**Comment by Mackel123** [comment]
> 关闭了，可以暂时改改，自用离线歌单

那之后打算怎么发展呀？感觉关闭了怪可惜的，不过果然这种第三方还是平台小一点才能生存，如果太广泛了就有可能被叮嘱～毕竟床上也是要吃饭的嘛～

**Comment by Mackel123** [comment]
> 原本正在重构2.0，等2.0重构好了再做打算吧

好的～期待进步

**Comment by hfun2017** [comment]
Ubuntu好不容易找到一个好用的播放器
