### ISSUE TITLE
心疼楼主

### ISSUE THREAD

**Issue by kakalote2008** [sunzongzheng/music#87]
一直关注这个项目，楼主确实做了不少工作，不过版权确实一直有问题，很难做大，但是必须要说一句，楼主一人之力，体验至少已经做到了这些大厂的7成，要知道这些大厂要做一样的事情，最少也需要50人以上。
PS：如果楼主有意在这个方向进一步发展，我可以帮忙楼主深度内推下某大厂，对，就是唯一没有给楼主发警告函的那个：）

**Comment by sunzongzheng** [comment]
之后会考虑这个方向的工作，有需求再拜托大佬 😄 

感谢支持~
