### ISSUE TITLE
qq音乐不能听了

### ISSUE THREAD

**Issue by wunianyoung** [sunzongzheng/music#93]
前几天还可以

**Comment by sunzongzheng** [comment]
更新@suen/music-api库，解决了部分歌曲试听问题。
剩下依旧不能听的可能是目前web版QQ音乐部分歌曲限制了客户端播放，这个问题不确定是否有解，如果无解之后会在`歌曲置灰规则`中加入

**Comment by sunzongzheng** [comment]
已解决，再次更新@suen/music-api库
