### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by memoryskull** [sunzongzheng/music#94]
Hello @sunzongzheng 
I want to create my portfolio and, therefore, I am contributing with open source repositories.
I can present you with a logo that represents your project without any commitment.

Thanks for your time.
Cheers!

**Comment by sunzongzheng** [comment]
Thank you for your kindness, but my current logo is adjusted by the designer. I need interface design more now. If you are interested and time, consider contributing page design.
Thanks again
